server {
    listen       8080;
    server_name  localhost;

    # Health check endpoint
    location /health {
        access_log off;
        default_type application/json;
        return 200 '{"status":"healthy"}';
    }

    # Serve static assets
    location / {
        root   /usr/share/nginx/html;
        index  index.html index.htm;
        try_files $uri $uri/ /index.html;
    }

    # Custom error pages
    error_page   500 502 503 504  /50x.html;
    location = /50x.html {
        root   /usr/share/nginx/html;
    }
}
